//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeCategory
    {
        public int RecipeCategoryId { get; set; }
        public int RecipeId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
